### PR TITLE
Included get_parameter, param.db and related files

### PR DESCRIPTION
**Pull request by Rasilgon**
Hi @trotsiuk! 

As discussed in Include default Parameters for European tree species into R package? #57, I have included the parameter sets in the package internal data and create a function to access it (get_parameters).  I've also committed changes in related files (NAMESPACE, help and example files, etc.)

I have tested and checked the functionality and everything seems to be fine, so I think that it is ready to be included in the pkg. Let me know.

### CODE REVIEW

**Comment by trotsiuk** [comment]
Thanks @Rasilgon for a great work. I have merged now the pull request.

**Comment by Rasilgon** [comment]
Glad to contribute!  :) As you probably saw, I have not modified the description file (version or authors). I did not do it, because I do not know which exact criteria you follow for versions or authors/contributors.

Regardless of this, I wonder if you are considering  a new release in cran, after the bug fixes and the new function. Our partners still prefer to use the cran version of the package. However, this is not enough reason, I can always tell them to use the github version. 

Related to this, I do not mind contributing a bit more. For instance, do something about #73 . We can agree what is to be done, I will implement it. At the moment, I have some time to allocate to this kind of stuff, and to not make use of would be a waste ;)

**Comment by trotsiuk** [comment]
Yes, it would be good to make a new release and contribution will be also included into the description file. 
I can potentially do it in two weeks or so (sorry now a bit busy with personal things helping my family).

**Comment by Rasilgon** [comment]
No problem! I did not mean to push. It is definitively not urgent, just asking out of interest. :)

**Pull request merged**
